arch:
    - amd64
    - ppc64le
language: go

go:
    - 1.1
    - 1.2
    - tip
jobs:
 exclude:
    - go: 1.1
      arch: ppc64le
    - go: 1.2
      arch: ppc64le
    - go: 1.1
      arch: amd64
    - go: 1.2
      arch: amd64
    
      
install:
    - go get github.com/stretchr/testify

script:
    - go test
    - go test -tags 'prod'
